modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="moonwalkmod"
version="${version}"
displayName="MoonWalk Mod"
description='''
Press M to moonwalk: play a random Michael Jackson sound and float gently.
Any mob that stares at you takes damage.
'''

[[dependencies.moonwalkmod]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.moonwalkmod]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
